apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-preferred-deployment
  labels:
    app: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
        - name: nginx
          image: nginx
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: size
                operator: In
                values:
                - medium
          - weight: 50
            preference:
              matchExpressions:
              - key: size
                operator: In
                values:
                - small
